# Generated by Django 4.1.13 on 2024-03-14 12:36

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionimage',
            name='question',
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='test',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.DeleteModel(
            name='OptionImage',
        ),
        migrations.DeleteModel(
            name='QuestionImage',
        ),
    ]
