# Generated by Django 4.1.13 on 2024-03-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-submitted_time']},
        ),
    ]
